Updates for the VEW1D channel algorithm
adcirc/adcirc pull request #365
Opened 2023-12-28 16:23 UTC by shinbunya

Updates for the VEW1D channel algorithm

These updates include functionality enhancements as well as bug fixes.

2023-12-28 17:20 UTC, zcobell requested changes
Hey @shinbunya - just a couple requested changes for clarity and one thing that looks like it was deleted in error

2023-12-28 17:20 UTC, zcobell commented on src/read_input.F
> +      NAMELIST /channelWetPerimeterControl/ activateChannelWetPerimeter
Same as above

2023-12-28 17:20 UTC, zcobell commented on thirdparty/swan/SwanReadADCGrid.ftn90
> +!ADC            n3 = find(node_dict,ivert1)
Tagging @caseydietrich for awareness as he works on his implementation of a new version of SWAN

2023-12-28 17:39 UTC, shinbunya commented on prep/read_global.F
> +      NAMELIST /channelWetPerimeterControl/ activateChannelWetPerimeter
Would it be also reasonable if the namelist name `channelWetPerimeterControl` is swapped with `vew1DChannelControl` as this is not really relevant to wet/dry?
And this way the variable name `activateChannelWetPerimeter ` may stay as it is.

2023-12-28 17:39 UTC, shinbunya commented on src/nodalattr.F
> +      SUBROUTINE initChannelWetPerimeter()
Agreed.

2023-12-28 17:40 UTC, shinbunya commented on src/nodalattr.F
> +                IF (ManningsN(I).le.0d0) cycle ! Can use Cd where man <= 0
I'll check that. Thanks for catching this.

2023-12-28 18:16 UTC, zcobell commented on prep/read_global.F
> +      NAMELIST /channelWetPerimeterControl/ activateChannelWetPerimeter
I think that works. Then we can use that namelist in the future for other VEW parameters too.

2024-01-03 14:05 UTC, zcobell approved these changes

2024-01-03 14:05 UTC, merged