Main nws14 read option
adcirc/adcirc pull request #389
Opened 2024-04-11 18:48 UTC by dwirasae

# Description

Resurrect an approach reading NetCdf nws14 met files using all compute core to simultaneously read in data. This option is activated through specifying a namelist:
    
&WindGrib2NetCdf read_NWS14_NetCdf_using_core_0 = .false.

in fort.15. If this namelist is omitted or set to .true., a core 0 will read in met data and MPI broadcasts to all other compute cores. 

Faster runtime using this approach seen in some HPC systems is a primary reason to bring it back (as an option).   

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Bug fix with breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] Update to existing feature to add new functionality
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (feature that would cause existing functionality to not work as expected)

# Issue Number

# How Has This Been Tested?

The changes were tested on a few small test problems (Shinnecock, small global runs).

# Relevant Publications (if applicable)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing tests pass locally with my changes
- [ ] My code is up-to-date and tested with changes from the latest version of `main`

## If any of the above are not checked, please explain why:

# Further comments

2024-04-11 20:37 UTC, zcobell requested changes
Hi @dwirasae - Looks good. Couple minor changes and we'll get this merged

2024-04-11 20:37 UTC, zcobell commented on src/wind.F
> +#ifdef DATATIME
Should this be `DATETIME`?

2024-04-11 20:37 UTC, zcobell commented on src/wind.F
> +!#ifdef ADCNETCDF ! BEG ADCNETCDF
Please remove this commented out. block

2024-04-11 20:42 UTC, dwirasae commented on src/wind.F
> +#ifdef DATATIME
Yes.

2024-04-11 20:43 UTC, dwirasae commented on src/wind.F
> +!#ifdef ADCNETCDF ! BEG ADCNETCDF
Will do.

2024-04-12 20:19 UTC, zcobell commented
Looks good. Thanks @dwirasae! I'm going to compress these into a single commit and merge. Much appreciated.

2024-04-12 20:22 UTC, zcobell approved these changes

2024-04-12 20:22 UTC, merged